@TodoApi_HostAddress = https://localhost:7036

GET {{TodoApi_HostAddress}}/

###

GET {{TodoApi_HostAddress}}/todoitems

###

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json
{
  "name":"walk dog",
  "isComplete": true
}
###

GET {{TodoApi_HostAddress}}/todoitems/complete

###

GET {{TodoApi_HostAddress}}/todoitems/3

###

PUT {{TodoApi_HostAddress}}/todoitems/4
Content-Type: application/json
{
  "name": "wash the car",
  "isComplete": true
}
###

DELETE {{TodoApi_HostAddress}}/todoitems/2

###
