@TodoApi_HostAddress = https://localhost:7036

GET {{TodoApi_HostAddress}}/

###

GET {{TodoApi_HostAddress}}/todoitems

###

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json
{
  "name":"walk dog",
  "isComplete": true
}
###

GET {{TodoApi_HostAddress}}/todoitems/complete

###

@id=3
GET {{TodoApi_HostAddress}}/todoitems/{{id}}

###

@id=3
PUT {{TodoApi_HostAddress}}/todoitems/{{id}}
Content-Type: application/json
{
  "name": "wash the car",
  "isComplete": true
}
###
